; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F413CG]
platform = ststm32
board = genericSTM32F413CG
framework = arduino

; Serial port for uploading (change as needed)
upload_protocol = stlink

; Build flags
build_flags =
    -D HAL_CAN_MODULE_ENABLED
    -D HAL_UART_MODULE_ENABLED
    -std=gnu++17
    -I include
    -Wl,-u,_printf_float
    ; Version components - override in CI/CD for release builds
    ; -D VER_MAJOR=1
    ; -D VER_MINOR=0
    ; -D VER_PATCH=0
    ; -D VER_DIRTY=0

; Libraries
lib_deps =
    collin80/can_common@^0.3.0
    khoih-prog/STM32_PWM@^1.0.1
    stm32duino/STM32duino FreeRTOS@^10.3.2
    bblanchon/ArduinoJson@^7.2.0

; Monitor settings
monitor_speed = 115200

; Debug configuration
debug_tool = stlink
debug_init_break = tbreak setup
